-- MySQL Script generated by MySQL Workbench
-- Wed Aug 31 09:05:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bobeda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bobeda` ;

-- -----------------------------------------------------
-- Schema bobeda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bobeda` DEFAULT CHARACTER SET utf8mb4 ;
USE `bobeda` ;

-- -----------------------------------------------------
-- Table `bobeda`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bobeda`.`clientes` (
  `id` INT(11) NOT NULL,
  `cedula` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `genero` CHAR(1) NOT NULL,
  `estado` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bobeda`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bobeda`.`productos` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pCompra` DOUBLE NOT NULL,
  `pVenta` DOUBLE NOT NULL,
  `cBodega` INT(11) NOT NULL,
  `cMinima` INT(11) NOT NULL,
  `cmaxPer` INT(11) NOT NULL,
  `estado` CHAR(1) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bobeda`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bobeda`.`user` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `bobeda`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bobeda`.`ventas` (
  `codigo` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente` INT(11) NOT NULL,
  `producto` INT(11) NOT NULL,
  `cantidad` INT(11) NOT NULL,
  PRIMARY KEY (`codigo`),
  CONSTRAINT `FK_ventas_clientes`
    FOREIGN KEY (`cliente`)
    REFERENCES `bobeda`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ventas_productos`
    FOREIGN KEY (`producto`)
    REFERENCES `bobeda`.`productos` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;

CREATE INDEX `FK_ventas_clientes_idx` ON `bobeda`.`ventas` (`cliente` ASC) ;

CREATE INDEX `FK_ventas_productos_idx` ON `bobeda`.`ventas` (`producto` ASC) ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
